export enum ErrorCodes {
  NOT_FOUND = 'ERR_400_NOT_FOUND',
  DUPLICATED_KEY = 'ERR_400_DUPLICATE',
  INTERNAL_ERROR = 'ERR_500_INTERNAL',
  UNAUTHORIZED = 'ERR_403_UNAUTHORIZED',
  USER_NOT_IN_THE_REQUEST = 'ERR_500_DOES_NOT_EXIST_AN_USER_IN_THE_REQUEST',
}
